name: Deploy al Servidor Ubuntu

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Descarga todo el historial de Git

      - name: Verificar archivos en GitHub Actions
        run: |
          echo "Listando archivos en GitHub Actions:"
          ls -la
          echo "Verificando estructura de archivos:"
          find .

      - name: Agregar host SSH a known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}

      - name: Backup de la versión anterior en el servidor
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT || 22 }}
          script: |
            if [ -d "/var/www/parqueapp" ]; then
              TIMESTAMP=$(date +"%Y%m%d-%H%M%S")
              mv "/var/www/parqueapp" "/var/www/parqueapp_$TIMESTAMP"
            fi
            mkdir -p "/var/www/parqueapp"

      - name: Copiar archivos al servidor
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT || 22 }}
          source: "."  # Copia todos los archivos
          target: "/var/www/parqueapp"
          strip_components: 1

      - name: Ajustar permisos de archivos en el servidor
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT || 22 }}
          script: |
            sudo -S chown -R www-data:www-data /var/www/parqueapp
            sudo -S chmod -R 755 /var/www/parqueapp
            sudo -S systemctl restart apache2

      - name: Verificar contenido del repositorio
        run: git status

      - name: Verificar archivos ignorados
        run: git check-ignore -v *